#!/usr/bin/env bash
# TokenSmart — provision a LocalStack KMS key for integration tests.
#
# Expects the LocalStack service from docker-compose.test.yml to be healthy:
#   docker compose -f docker-compose.test.yml up -d localstack
#
# Writes the test CMK ARN to stdout AND to `.localstack-kms.env` so the
# gateway test suite can pick it up automatically. Safe to re-run: creates
# a new CMK each time (idempotency isn't worth the extra round-trip).

set -euo pipefail

ENDPOINT="${TOKENSMART_KMS_ENDPOINT_URL:-http://localhost:4566}"
REGION="${AWS_REGION:-us-east-1}"

# LocalStack accepts any dummy credentials; the SDK just needs them set.
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-test}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-test}"
export AWS_DEFAULT_REGION="$REGION"

# Health check — fail fast with a readable message instead of a long SDK stack.
if ! curl -sf "$ENDPOINT/_localstack/health" >/dev/null; then
    echo "❌ LocalStack not reachable at $ENDPOINT" >&2
    echo "   Run: docker compose -f docker-compose.test.yml up -d localstack" >&2
    exit 1
fi

# Check for `aws` CLI. Most dev environments have it; if not, use the
# localstack docker container's embedded awslocal via exec.
if command -v aws >/dev/null 2>&1; then
    CREATE_KEY_CMD=(aws --endpoint-url "$ENDPOINT" kms create-key --description "tokensmart-test-cmk")
else
    CREATE_KEY_CMD=(docker exec -i tokensmart-localstack awslocal kms create-key --description "tokensmart-test-cmk")
fi

RESULT=$("${CREATE_KEY_CMD[@]}")
KEY_ID=$(echo "$RESULT" | grep -o '"KeyId": *"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
ARN=$(echo "$RESULT" | grep -o '"Arn": *"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')

if [[ -z "$ARN" ]]; then
    echo "❌ Failed to parse CMK ARN from CreateKey response:" >&2
    echo "$RESULT" >&2
    exit 1
fi

# Persist so the test runner can source this file.
cat > .localstack-kms.env <<EOF
# Generated by scripts/test-setup-localstack.sh — safe to regenerate.
export TOKENSMART_KMS_KEY_ARN="$ARN"
export TOKENSMART_KMS_ENDPOINT_URL="$ENDPOINT"
export AWS_REGION="$REGION"
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
EOF

echo "[localstack-setup] CMK created: $ARN"
echo "[localstack-setup] wrote .localstack-kms.env — source it to run tests:"
echo "                    source .localstack-kms.env && cd apps/gateway && bun test"
