import type { ReactNode } from "react";
import Link from "next/link";
import { redirect, notFound } from "next/navigation";
import { getSession, isAuthEnabled } from "@/lib/auth";
import { getProjectForUser, sql } from "@/lib/db";
import {
  fmtMicroCentsUsd,
  getLearningCostSummary,
  listProjectPolicies,
} from "@/lib/policy-history";
import type {
  LearningCostSummary,
  ProjectPolicyRow,
  PolicyStatus,
} from "@/lib/policy-history";
import { planAllows, minPlanForEntitlement } from "@/lib/plans";
import { Sparkline } from "@/components/Sparkline";
import {
  setLearningEnabledAction,
  rollbackPolicyAction,
} from "./actions";
import { getDictionary } from "@/lib/i18n.server";
import type { Dictionary } from "@/i18n/types";

export const dynamic = "force-dynamic";
export const revalidate = 0;

/**
 * Per-project policy changelog.
 *
 * One row per policy version generated by the retrain pipeline. The
 * goal is to make the "what did the cron do last night?" question
 * answerable from a single page — exactly the visibility paid users
 * need to feel like the learning subscription is doing something.
 *
 * Rollback / promote actions are deliberately NOT in this MVP. Until
 * we've watched a few real customers' retrain output for a couple of
 * weeks, the right shape for those controls (per-version button? a
 * separate "rollback to v17" workflow with a confirmation modal?) is
 * a guess. Better to ship read-only first and iterate.
 */

function fmtDateTime(d: Date | null, locale: string): string {
  if (!d) return "—";
  return new Intl.DateTimeFormat(locale === "zh-CN" ? "zh-CN" : "en-US", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  }).format(new Date(d));
}

function statusPillClass(status: PolicyStatus): string {
  switch (status) {
    case "active":
      return "pill pill-success";
    case "pending":
      return "pill pill-warning";
    case "superseded":
      return "pill pill-neutral";
    case "rejected":
      return "pill pill-danger";
  }
}

export default async function ProjectPolicyChangelogPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ toast?: string; to?: string; new?: string; detail?: string }>;
}) {
  if (!isAuthEnabled()) redirect("/");
  const session = await getSession();
  if (!session) redirect("/login");

  const { id: projectId } = await params;
  const sp = await searchParams;
  const project = await getProjectForUser(session.user.id, projectId);
  if (!project) notFound();

  let rows: ProjectPolicyRow[] = [];
  let dbError: string | null = null;
  let learningEnabled = false;
  let costSummary: LearningCostSummary | null = null;
  try {
    rows = await listProjectPolicies(projectId, 50);
    const flag = await sql<{ learning_enabled: boolean }[]>`
      SELECT learning_enabled FROM projects WHERE id = ${projectId}
    `;
    learningEnabled = flag[0]?.learning_enabled ?? false;
    costSummary = await getLearningCostSummary(projectId);
  } catch (err) {
    dbError = err instanceof Error ? err.message : String(err);
  }

  const activeRow = rows.find((r) => r.status === "active") ?? null;
  const canTrain = planAllows(session.user.plan, "background_policy_training");
  const requiredPlanName = minPlanForEntitlement(
    "background_policy_training"
  ).name;

  const { locale, t } = await getDictionary();
  const tp = t.routingPolicy;

  return (
    <main>
      <Link href={`/projects/${projectId}`} className="back-link">
        ← {project.name}
      </Link>
      <h1>{tp.title}</h1>
      <p className="tagline">{tp.tagline}</p>

      {sp.toast && (
        <ToastBanner toast={sp.toast} sp={sp} tp={tp} />
      )}

      {/* Active policy summary card. The "what's running RIGHT NOW"
          question deserves answer in one glance. Below it is the full
          history table. The pause/resume toggle lives here too — it's
          the operator's main lever on this page. */}
      <div className="card">
        <div className="card-header">
          <h2>{tp.activeTitle}</h2>
          <div className="card-header-spacer" />
          <form action={setLearningEnabledAction} style={{ margin: 0 }}>
            <input type="hidden" name="project_id" value={projectId} />
            <input
              type="hidden"
              name="enabled"
              value={String(!learningEnabled)}
            />
            <button
              type="submit"
              className={`btn btn-sm ${learningEnabled ? "btn-ghost" : "btn-primary"}`}
              disabled={!canTrain && !learningEnabled}
              title={
                !canTrain && !learningEnabled
                  ? tp.upgradeRequiredTooltipTpl.replace(
                      "{plan}",
                      requiredPlanName
                    )
                  : learningEnabled
                    ? tp.pauseTooltip
                    : tp.resumeTooltip
              }
            >
              {learningEnabled ? tp.pauseLearningBtn : tp.resumeLearningBtn}
            </button>
          </form>
        </div>
        {activeRow ? (
          <div style={{ display: "grid", gap: 8, padding: "8px 0" }}>
            <div>
              <span className="pill pill-success">v{activeRow.version}</span>{" "}
              <span style={{ color: "var(--text-muted)", fontSize: 13 }}>
                {tp.activeStatusTpl
                  .replace(
                    "{date}",
                    fmtDateTime(activeRow.activated_at, locale)
                  )
                  .replace(
                    "{n}",
                    activeRow.sample_count.toLocaleString()
                  )
                  .replace(
                    "{noun}",
                    activeRow.sample_count === 1
                      ? tp.activeSampleSingular
                      : tp.activeSamplePlural
                  )}
              </span>
            </div>
            {activeRow.notes && (
              <div
                style={{
                  fontSize: 13,
                  color: "var(--text-muted)",
                  whiteSpace: "pre-wrap",
                }}
              >
                {activeRow.notes}
              </div>
            )}
            <div style={{ fontSize: 12, color: "var(--text-muted)" }}>
              {tp.learningStatusPrefix}
              <strong>
                {learningEnabled
                  ? tp.learningStatusOn
                  : tp.learningStatusOff}
              </strong>
              .{" "}
              {learningEnabled ? tp.learningOnNote : tp.learningPausedNote}
            </div>
          </div>
        ) : (
          <div className="empty">
            {tp.noActiveBodyPrefix}
            <ol
              style={{
                margin: "8px 0 4px 18px",
                paddingLeft: 0,
                fontSize: 13,
              }}
            >
              <li>
                {tp.noActiveStep1Prefix}
                <Link href={`/projects/${projectId}#routing`}>
                  {tp.noActiveStep1Link}
                </Link>
                {tp.noActiveStep1Mid}
                <code>{tp.noActiveStep1Mode1}</code>
                {tp.noActiveStep1Or}
                <code>{tp.noActiveStep1Mode2}</code>
                {tp.noActiveStep1Sample}
                <em>{tp.noActiveStep1ChipPrefix}</em>
                {tp.noActiveStep1ChipSuffix}
                <code style={{ whiteSpace: "nowrap" }}>
                  {tp.noActiveStep1CliPrefix}
                </code>
                {tp.noActiveStep1CliSuffix}
              </li>
              <li>
                {tp.noActiveStep2Prefix}
                <code style={{ whiteSpace: "nowrap" }}>
                  {tp.noActiveStep2Mid}
                  {projectId}
                </code>
                {tp.noActiveStep2Suffix}
              </li>
            </ol>
          </div>
        )}
      </div>

      {!dbError && costSummary && (
        <LearningCostCard
          summary={costSummary}
          learningEnabled={learningEnabled}
          tp={tp}
          locale={locale}
        />
      )}

      {dbError && (
        <div className="card card-danger">
          <strong>{tp.dbErrTitle}</strong>
          <br />
          <span style={{ color: "var(--text-muted)", fontSize: 12 }}>
            {dbError}
          </span>
        </div>
      )}

      {!dbError && (
        <div className="card">
          <div className="card-header">
            <h2>{tp.historyTitle}</h2>
            <div className="card-header-spacer" />
            <span style={{ color: "var(--text-muted)", fontSize: 12 }}>
              {rows.length}
              {rows.length === 1
                ? tp.historyVersionsSingular
                : tp.historyVersionsPlural}
            </span>
          </div>
          {rows.length === 0 ? (
            <div className="empty">{tp.historyEmpty}</div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th style={{ width: 80 }}>{tp.colVersion}</th>
                  <th style={{ width: 100 }}>{tp.colStatus}</th>
                  <th style={{ width: 100 }}>{tp.colSource}</th>
                  <th style={{ width: 110 }}>{tp.colSamples}</th>
                  <th>{tp.colNotes}</th>
                  <th style={{ width: 170 }}>{tp.colGenerated}</th>
                  <th style={{ width: 110 }}></th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id}>
                    <td>
                      <strong>v{r.version}</strong>
                    </td>
                    <td>
                      <span className={statusPillClass(r.status)}>
                        {r.status}
                      </span>
                    </td>
                    <td>
                      <span
                        style={{ color: "var(--text-muted)", fontSize: 12 }}
                      >
                        {r.source}
                      </span>
                    </td>
                    <td
                      style={{
                        textAlign: "right",
                        fontVariantNumeric: "tabular-nums",
                      }}
                    >
                      {r.sample_count.toLocaleString()}
                    </td>
                    <td style={{ fontSize: 13 }}>
                      {r.notes ?? (
                        <em style={{ color: "var(--text-muted)" }}>—</em>
                      )}
                    </td>
                    <td style={{ fontSize: 12, color: "var(--text-muted)" }}>
                      {fmtDateTime(r.generated_at, locale)}
                    </td>
                    <td style={{ textAlign: "right" }}>
                      {r.status === "superseded" ? (
                        <form
                          action={rollbackPolicyAction}
                          style={{ margin: 0 }}
                        >
                          <input
                            type="hidden"
                            name="project_id"
                            value={projectId}
                          />
                          <input
                            type="hidden"
                            name="version"
                            value={String(r.version)}
                          />
                          <button
                            type="submit"
                            className="btn btn-sm btn-ghost"
                            disabled={!canTrain}
                            title={
                              canTrain
                                ? tp.rollbackTooltipReadyTpl.replace(
                                    "{n}",
                                    String(r.version)
                                  )
                                : tp.rollbackTooltipGatedTpl.replace(
                                    "{plan}",
                                    requiredPlanName
                                  )
                            }
                          >
                            {tp.rollbackBtnTpl.replace(
                              "{n}",
                              String(r.version)
                            )}
                          </button>
                        </form>
                      ) : null}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      <div className="card" style={{ background: "var(--bg-subtle)" }}>
        <div className="card-header">
          <h2 style={{ fontSize: 14 }}>{tp.howTitle}</h2>
        </div>
        <div
          style={{
            fontSize: 13,
            color: "var(--text-muted)",
            display: "grid",
            gap: 6,
          }}
        >
          <p style={{ margin: 0 }}>{tp.howBody1}</p>
          <p style={{ margin: 0 }}>
            {tp.howBody2Prefix}
            <code>
              bun run retrain-project -- --project {projectId}
            </code>
            {tp.howBody2Suffix}
          </p>
        </div>
      </div>
    </main>
  );
}

function LearningCostCard({
  summary,
  learningEnabled,
  tp,
  locale,
}: {
  summary: LearningCostSummary;
  learningEnabled: boolean;
  tp: Dictionary["routingPolicy"];
  locale: string;
}) {
  // Empty-state branch. When the project has never run a shadow A/B
  // call, the data grid would just say "$0.00 / 0 / —" three times,
  // which is a dead-end. Replace it with an actionable nudge so the
  // user sees what to do next instead of a wall of zeros.
  const noShadowYet =
    summary.trailing_30d_calls === 0 &&
    summary.month_to_date_calls === 0 &&
    !summary.last_shadow_at;

  if (noShadowYet) {
    return (
      <CostCardEmptyState learningEnabled={learningEnabled} tp={tp} />
    );
  }

  const mtdUsd = fmtMicroCentsUsd(summary.month_to_date_uc);
  const trailingUsd = fmtMicroCentsUsd(summary.trailing_30d_uc);
  // Average cost per shadow call in the trailing window — useful for
  // operators sanity-checking "is each shadow call really 1/10th of a
  // cent?" before opening tickets about runaway billing.
  const avgPerCallUsd =
    summary.trailing_30d_calls > 0
      ? fmtMicroCentsUsd(
          summary.trailing_30d_uc / BigInt(summary.trailing_30d_calls)
        )
      : "—";
  const lastSeen = summary.last_shadow_at
    ? new Intl.DateTimeFormat(locale === "zh-CN" ? "zh-CN" : "en-US", {
        month: "short",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
      }).format(new Date(summary.last_shadow_at))
    : null;
  const peakUsd = fmtMicroCentsUsd(
    BigInt(Math.max(0, ...summary.trailing_30d_daily_uc))
  );

  return (
    <div className="card">
      <div className="card-header">
        <h2>{tp.costTitle}</h2>
        <div className="card-header-spacer" />
        <span style={{ color: "var(--text-muted)", fontSize: 12 }}>
          {tp.costSubLabel}
        </span>
      </div>

      <div
        style={{
          display: "grid",
          gap: 16,
          gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
          padding: "8px 0 4px",
        }}
      >
        <div>
          <div
            style={{
              fontSize: 11,
              color: "var(--text-muted)",
              textTransform: "uppercase",
              letterSpacing: 0.5,
            }}
          >
            {tp.costMtdLabel}
          </div>
          <div
            style={{
              fontSize: 22,
              fontWeight: 600,
              fontVariantNumeric: "tabular-nums",
            }}
          >
            {mtdUsd}
          </div>
          <div style={{ fontSize: 12, color: "var(--text-muted)" }}>
            {summary.month_to_date_calls.toLocaleString()}
            {summary.month_to_date_calls === 1
              ? tp.costMtdShadowSingular
              : tp.costMtdShadowPlural}
          </div>
        </div>

        <div>
          <div
            style={{
              fontSize: 11,
              color: "var(--text-muted)",
              textTransform: "uppercase",
              letterSpacing: 0.5,
            }}
          >
            {tp.costTrailing30dLabel}
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              marginTop: 2,
            }}
          >
            <span
              style={{
                fontSize: 22,
                fontWeight: 600,
                fontVariantNumeric: "tabular-nums",
              }}
            >
              {trailingUsd}
            </span>
            <span
              style={{ color: "var(--text-muted)", flexShrink: 0 }}
              title={tp.costSparklineTooltipTpl.replace("{peak}", peakUsd)}
            >
              <Sparkline
                values={summary.trailing_30d_daily_uc}
                width={84}
                height={24}
              />
            </span>
          </div>
          <div style={{ fontSize: 12, color: "var(--text-muted)" }}>
            {tp.costTrailing30dAvgPrefix}
            {avgPerCallUsd}
            {tp.costTrailing30dAvgSuffix}
          </div>
        </div>

        <div>
          <div
            style={{
              fontSize: 11,
              color: "var(--text-muted)",
              textTransform: "uppercase",
              letterSpacing: 0.5,
            }}
          >
            {tp.costLastShadowLabel}
          </div>
          <div style={{ fontSize: 22, fontWeight: 600 }}>
            {lastSeen ?? "—"}
          </div>
          <div style={{ fontSize: 12, color: "var(--text-muted)" }}>
            {learningEnabled ? tp.costLearningOn : tp.costLearningPaused}
          </div>
        </div>
      </div>

      <div
        style={{
          fontSize: 12,
          color: "var(--text-muted)",
          marginTop: 12,
          paddingTop: 10,
          borderTop: "1px solid var(--border)",
        }}
      >
        {tp.costFooterPrefix}
        <code>--sample-rate</code>
        {tp.costFooterMid}
        &quot;{tp.pauseLearningBtn}&quot;
        {tp.costFooterSuffix}
      </div>
    </div>
  );
}

/**
 * Empty-state card shown in place of LearningCostCard when no shadow
 * A/B traffic has ever landed for this project. Without it, fresh
 * projects see "$0.00 / 0 / —" three times — informative-zero, but a
 * dead-end. With it, they see a clear "do this next" nudge.
 *
 * Distinguishes the two reasons there's no data:
 *   - learning is OFF — fix that toggle first
 *   - learning is ON but no shadow rule fires yet — set one up
 */
function CostCardEmptyState({
  learningEnabled,
  tp,
}: {
  learningEnabled: boolean;
  tp: Dictionary["routingPolicy"];
}) {
  return (
    <div className="card">
      <div className="card-header">
        <h2>{tp.costTitle}</h2>
        <div className="card-header-spacer" />
        <span style={{ color: "var(--text-muted)", fontSize: 12 }}>
          {tp.costSubLabel}
        </span>
      </div>
      <div className="empty">
        {learningEnabled ? (
          <>
            <strong>{tp.costEmptyEnabledTitle}</strong>
            {tp.costEmptyEnabledBody}
            <div
              style={{
                fontSize: 12,
                marginTop: 8,
                color: "var(--text-muted)",
              }}
            >
              {tp.costEmptyEnabledTipBody}
            </div>
            <div style={{ fontSize: 12, marginTop: 8 }}>
              {tp.costEmptyEnabledCliHint}
              <pre
                style={{
                  background: "var(--bg-subtle)",
                  padding: 10,
                  borderRadius: 6,
                  fontSize: 12,
                  marginTop: 6,
                  overflowX: "auto",
                }}
              >
                {`bun run set-routing -- \\
  --project <project-id> \\
  --from "your-current-model" \\
  --to "candidate-model" \\
  --mode shadow \\
  --sample-rate 0.05`}
              </pre>
            </div>
          </>
        ) : (
          <>
            <strong>{tp.costEmptyPausedTitle}</strong>
            {tp.costEmptyPausedBody}
          </>
        )}
      </div>
    </div>
  );
}

function ToastBanner({
  toast,
  sp,
  tp,
}: {
  toast: string;
  sp: { to?: string; new?: string; detail?: string };
  tp: Dictionary["routingPolicy"];
}) {
  const messages: Record<
    string,
    { tone: "success" | "warning" | "danger"; text: ReactNode }
  > = {
    learning_paused: {
      tone: "warning",
      text: tp.toastLearningPaused,
    },
    learning_resumed: {
      tone: "success",
      text: tp.toastLearningResumed,
    },
    upgrade_required_for_learning: {
      tone: "warning",
      text: (
        <>
          {tp.toastUpgradeRequiredPrefix}
          <Link href="/billing" style={{ color: "var(--accent)" }}>
            {tp.toastUpgradeRequiredLink}
          </Link>
          {tp.toastUpgradeRequiredSuffix}
        </>
      ),
    },
    rollback_complete: {
      tone: "success",
      text: tp.toastRollbackCompleteTpl
        .replace("{from}", sp.to ?? "?")
        .replace("{to}", sp.new ?? "?"),
    },
    rollback_failed: {
      tone: "danger",
      text: tp.toastRollbackFailedTpl.replace(
        "{detail}",
        sp.detail ?? tp.toastRollbackFailedNoDetail
      ),
    },
  };
  const m = messages[toast];
  if (!m) return null;
  return (
    <div className={`card card-${m.tone}`} style={{ marginBottom: 12 }}>
      <div style={{ fontSize: 13 }}>{m.text}</div>
    </div>
  );
}
